source "http://rubygems.org"

# iruby dependencies
gem 'rbczmq'
gem 'ffi-rzmq'
gem 'iruby'

# datatables
gemspec  :path => '../../'

# daru
gem "daru", git: 'https://github.com/shekharrajak/daru.git', :branch => 'html_table_with_id'

# gem "daru", path: '/Users/shekharrajak/Documents/gsoc17/daru'
